<template>
  <div class="about">
    <div class="num">
        <button @click="tables">TABLE</button>
        <button @click="spheres">SPHERE</button>
        <button @click="lotterys">转动</button>
        <button @click="stops">停止</button>
        <button @click="resets">复位</button>
    </div>
    <Threed ref="threed" :table="tableData"/>
  </div>
</template>

<script>
import Threed from '../components/threeD.vue'
export default {
  name: 'About',
  components: {
    Threed
  },
  data () {
    return {
      tableData: [{
        name: 'Hydrogen', // 名称
        x: 1, // x轴位置
        y: 1 //  y轴位置
      }, {
        name: 'Hydrogen',
        x: 1,
        y: 2
      }, {
        name: 'Hydrogen',
        x: 1,
        y: 3
      }, {
        name: 'Hydrogen',
        x: 1,
        y: 4
      }, {
        name: 'Hydrogen',
        x: 1,
        y: 5
      }, {
        name: 'Hydrogen',
        x: 1,
        y: 6
      }, {
        name: 'Hydrogen',
        x: 1,
        y: 7
      }, {
        name: 'Hydrogen',
        x: 1,
        y: 8
      }, {
        name: 'Hydrogen',
        x: 1,
        y: 9
      }, {
        name: 'Hydrogen',
        x: 1,
        y: 10
      }, {
        name: 'Hydrogen',
        x: 2,
        y: 1
      }, {
        name: 'Hydrogen',
        x: 2,
        y: 2
      }, {
        name: 'Hydrogen',
        x: 2,
        y: 3
      }, {
        name: 'Hydrogen',
        x: 2,
        y: 4
      }, {
        name: 'Hydrogen',
        x: 2,
        y: 5
      }, {
        name: 'Hydrogen',
        x: 2,
        y: 6
      }, {
        name: 'Hydrogen',
        x: 2,
        y: 7
      }, {
        name: 'Hydrogen',
        x: 2,
        y: 8
      }, {
        name: 'Hydrogen',
        x: 2,
        y: 9
      }, {
        name: 'Hydrogen',
        x: 2,
        y: 10
      }, {
        name: 'Hydrogen',
        x: 3,
        y: 1
      }, {
        name: 'Hydrogen',
        x: 3,
        y: 2
      }, {
        name: 'Hydrogen',
        x: 3,
        y: 3
      }, {
        name: 'Hydrogen',
        x: 3,
        y: 4
      }, {
        name: 'Hydrogen',
        x: 3,
        y: 5
      }, {
        name: 'Hydrogen',
        x: 3,
        y: 6
      }, {
        name: 'Hydrogen',
        x: 3,
        y: 7
      }, {
        name: 'Hydrogen',
        x: 3,
        y: 8
      }, {
        name: 'Hydrogen',
        x: 3,
        y: 9
      }, {
        name: 'Hydrogen',
        x: 3,
        y: 10
      }, {
        name: 'Hydrogen',
        x: 4,
        y: 1
      }, {
        name: 'Hydrogen',
        x: 4,
        y: 2
      }, {
        name: 'Hydrogen',
        x: 4,
        y: 3
      }, {
        name: 'Hydrogen',
        x: 4,
        y: 4
      }, {
        name: 'Hydrogen',
        x: 4,
        y: 5
      }, {
        name: 'Hydrogen',
        x: 4,
        y: 6
      }, {
        name: 'Hydrogen',
        x: 4,
        y: 7
      }, {
        name: 'Hydrogen',
        x: 4,
        y: 8
      }, {
        name: 'Hydrogen',
        x: 4,
        y: 9
      }, {
        name: 'Hydrogen',
        x: 4,
        y: 10
      }, {
        name: 'Hydrogen',
        x: 5,
        y: 1
      }, {
        name: 'Hydrogen',
        x: 5,
        y: 2
      }, {
        name: 'Hydrogen',
        x: 5,
        y: 3
      }, {
        name: 'Hydrogen',
        x: 5,
        y: 4
      }, {
        name: 'Hydrogen',
        x: 5,
        y: 5
      }, {
        name: 'Hydrogen',
        x: 5,
        y: 6
      }, {
        name: 'Hydrogen',
        x: 5,
        y: 7
      }, {
        name: 'Hydrogen',
        x: 5,
        y: 8
      }, {
        name: 'Hydrogen',
        x: 5,
        y: 9
      }, {
        name: 'Hydrogen',
        x: 5,
        y: 10
      }, {
        name: 'Hydrogen',
        x: 6,
        y: 1
      }, {
        name: 'Hydrogen',
        x: 6,
        y: 2
      }, {
        name: 'Hydrogen',
        x: 6,
        y: 3
      }, {
        name: 'Hydrogen',
        x: 6,
        y: 4
      }, {
        name: 'Hydrogen',
        x: 6,
        y: 5
      }, {
        name: 'Hydrogen',
        x: 6,
        y: 6
      }, {
        name: 'Hydrogen',
        x: 6,
        y: 7
      }, {
        name: 'Hydrogen',
        x: 6,
        y: 8
      }, {
        name: 'Hydrogen',
        x: 6,
        y: 9
      }, {
        name: 'Hydrogen',
        x: 6,
        y: 10
      }, {
        name: 'Hydrogen',
        x: 7,
        y: 1
      }, {
        name: 'Hydrogen',
        x: 7,
        y: 2
      }, {
        name: 'Hydrogen',
        x: 7,
        y: 3
      }, {
        name: 'Hydrogen',
        x: 7,
        y: 4
      }, {
        name: 'Hydrogen',
        x: 7,
        y: 5
      }, {
        name: 'Hydrogen',
        x: 7,
        y: 6
      }, {
        name: 'Hydrogen',
        x: 7,
        y: 7
      }, {
        name: 'Hydrogen',
        x: 7,
        y: 8
      }, {
        name: 'Hydrogen',
        x: 7,
        y: 9
      }, {
        name: 'Hydrogen',
        x: 7,
        y: 10
      }, {
        name: 'Hydrogen',
        x: 8,
        y: 1
      }, {
        name: 'Hydrogen',
        x: 8,
        y: 2
      }, {
        name: 'Hydrogen',
        x: 8,
        y: 3
      }, {
        name: 'Hydrogen',
        x: 8,
        y: 4
      }, {
        name: 'Hydrogen',
        x: 8,
        y: 5
      }, {
        name: 'Hydrogen',
        x: 8,
        y: 6
      }, {
        name: 'Hydrogen',
        x: 8,
        y: 7
      }, {
        name: 'Hydrogen',
        x: 8,
        y: 8
      }, {
        name: 'Hydrogen',
        x: 8,
        y: 9
      }, {
        name: 'Hydrogen',
        x: 8,
        y: 10
      }, {
        name: 'Hydrogen',
        x: 9,
        y: 1
      }, {
        name: 'Hydrogen',
        x: 9,
        y: 2
      }, {
        name: 'Hydrogen',
        x: 9,
        y: 3
      }, {
        name: 'Hydrogen',
        x: 9,
        y: 4
      }, {
        name: 'Hydrogen',
        x: 9,
        y: 5
      }, {
        name: 'Hydrogen',
        x: 9,
        y: 6
      }, {
        name: 'Hydrogen',
        x: 9,
        y: 7
      }, {
        name: 'Hydrogen',
        x: 9,
        y: 8
      }, {
        name: 'Hydrogen',
        x: 9,
        y: 9
      }, {
        name: 'Hydrogen',
        x: 9,
        y: 10
      }, {
        name: 'Hydrogen',
        x: 10,
        y: 1
      }, {
        name: 'Hydrogen',
        x: 10,
        y: 2
      }, {
        name: 'Hydrogen',
        x: 10,
        y: 3
      }, {
        name: 'Hydrogen',
        x: 10,
        y: 4
      }, {
        name: 'Hydrogen',
        x: 10,
        y: 5
      }, {
        name: 'Hydrogen',
        x: 10,
        y: 6
      }, {
        name: 'Hydrogen',
        x: 10,
        y: 7
      }, {
        name: 'Hydrogen',
        x: 10,
        y: 8
      }, {
        name: '王二蛋子',
        x: 10,
        y: 9
      }, {
        name: 'Hydrogen',
        x: 10,
        y: 10
      }]
    }
  },
  mounted () {
  },
  methods: {
    tables () {
      this.$refs.threed.tables()
    },
    spheres () {
      this.$refs.threed.spheres()
    },
    lotterys () {
      this.$refs.threed.lotterys()
    },
    stops () {
      this.$refs.threed.stops()
    },
    resets () {
      this.$refs.threed.resets()
    }
  }
}
</script>

<style lang="scss">
.about{
  .num{
    position: fixed;
    z-index: 20;
  }
}
</style>
